// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ProjectItems__FormController from "./project_items/form_controller"
application.register("project-items--form", ProjectItems__FormController)

import Quotes__FormController from "./quotes/form_controller"
application.register("quotes--form", Quotes__FormController)
